### ISSUE TITLE
Support for .net standard

### ISSUE THREAD

**Issue by simonholt** [markwhitaker/RegexToolbox.CSharp#3]
May I humbly suggest targeting .net standard with this library?  It should be possible to target .netstandard1.0, which means it will be able to run against pretty much anything - including .net core and Xamarin.

**Comment by markwhitaker** [comment]
Cheers Simon, I'll look into it.

**Comment by markwhitaker** [comment]
Sorry it's taken me a while to reply to this! For now, and given where all my work happens, I'm more interested in maintaining compatibility with previous versions of Visual Studio than targeting Xamarin and the like. I just don't see the uptake in those technologies to justify it. But that would make a great fork project so by all means feel free to go that way if you like?
